export const SET_MAINTENENCE_SERVICE = 'SET_MAINTENENCE_SERVICE'
export const SET_INTERNET_SERVICE = 'SET_INTERNET_SERVICE'
export const SET_API_RESULT = 'SET_API_RESULT'
export const SET_INPUT_DATA = 'SET_INPUT_DATA'


export const SET_API_JSON = 'SET_API_JSON'
export const SET_API_JSON_ERROR = 'SET_API_JSON_ERROR'
export const SET_TRIP_FORM = 'SET_TRIP_FORM'
export const SET_TRIP_STEP = 'SET_TRIP_STEP'
export const SET_CREATE_TRIP_JSON = 'SET_CREATE_TRIP_JSON'
export const SET_SUB_MODAL = 'SET_SUB_MODAL'

export const SET_TYT_USER = 'SET_TYT_USER'
export const SET_OTP ='SET_OTP'

export const SET_PANEL_TITLE ='SET_PANEL_TITLE'

export const SET_TRACK_AND_TRACE ='SET_TRACK_TRACE'
export const SET_PAGE_LIMIT ='SET_PAGE_LIMIT'
export const SET_PAGINATION ='SET_PAGINATION'
export const GET_SUB= "GET_SUB"
export const GET_CURRENT_PLAN = 'GET_CURRENT_PLAN'
export const SET_ECHALLAN_DATA = 'SET_ECHALLAN_DATA'

export const RETURN_TRIP_JSON = 'RETURN_TRIP_JSON'
export const SET_RETURN_TRIP_VIEW = 'SET_RETURN_TRIP_VIEW'


export const SET_PDF_ADS = 'SET_PDF_ADS'

